layout_spectrum: 0.7768915
typography_spectrum: 0.1938669
color:
  saturation: 0.4564077
  lightness: 0.4943551
  brandStrength: 0.2275697
  rhythmicContrast: 0.7224833
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
name: Maxegan
